// Code generated by mockery v2.26.1. DO NOT EDIT.

package command

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAddFileUsecase is an autogenerated mock type for the AddFileUsecase type
type MockAddFileUsecase struct {
	mock.Mock
}

type MockAddFileUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddFileUsecase) EXPECT() *MockAddFileUsecase_Expecter {
	return &MockAddFileUsecase_Expecter{mock: &_m.Mock}
}

// AddFile provides a mock function with given fields: ctx, name, data, lockPassword
func (_m *MockAddFileUsecase) AddFile(ctx context.Context, name string, data []byte, lockPassword string) error {
	ret := _m.Called(ctx, name, data, lockPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) error); ok {
		r0 = rf(ctx, name, data, lockPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAddFileUsecase_AddFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFile'
type MockAddFileUsecase_AddFile_Call struct {
	*mock.Call
}

// AddFile is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - data []byte
//   - lockPassword string
func (_e *MockAddFileUsecase_Expecter) AddFile(ctx interface{}, name interface{}, data interface{}, lockPassword interface{}) *MockAddFileUsecase_AddFile_Call {
	return &MockAddFileUsecase_AddFile_Call{Call: _e.mock.On("AddFile", ctx, name, data, lockPassword)}
}

func (_c *MockAddFileUsecase_AddFile_Call) Run(run func(ctx context.Context, name string, data []byte, lockPassword string)) *MockAddFileUsecase_AddFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *MockAddFileUsecase_AddFile_Call) Return(_a0 error) *MockAddFileUsecase_AddFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAddFileUsecase_AddFile_Call) RunAndReturn(run func(context.Context, string, []byte, string) error) *MockAddFileUsecase_AddFile_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractUserError provides a mock function with given fields: err
func (_m *MockAddFileUsecase) ExtractUserError(err error) error {
	ret := _m.Called(err)

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAddFileUsecase_ExtractUserError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractUserError'
type MockAddFileUsecase_ExtractUserError_Call struct {
	*mock.Call
}

// ExtractUserError is a helper method to define mock.On call
//   - err error
func (_e *MockAddFileUsecase_Expecter) ExtractUserError(err interface{}) *MockAddFileUsecase_ExtractUserError_Call {
	return &MockAddFileUsecase_ExtractUserError_Call{Call: _e.mock.On("ExtractUserError", err)}
}

func (_c *MockAddFileUsecase_ExtractUserError_Call) Run(run func(err error)) *MockAddFileUsecase_ExtractUserError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockAddFileUsecase_ExtractUserError_Call) Return(_a0 error) *MockAddFileUsecase_ExtractUserError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAddFileUsecase_ExtractUserError_Call) RunAndReturn(run func(error) error) *MockAddFileUsecase_ExtractUserError_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function with given fields: ctx, path
func (_m *MockAddFileUsecase) ReadFile(ctx context.Context, path string) ([]byte, error) {
	ret := _m.Called(ctx, path)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAddFileUsecase_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockAddFileUsecase_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockAddFileUsecase_Expecter) ReadFile(ctx interface{}, path interface{}) *MockAddFileUsecase_ReadFile_Call {
	return &MockAddFileUsecase_ReadFile_Call{Call: _e.mock.On("ReadFile", ctx, path)}
}

func (_c *MockAddFileUsecase_ReadFile_Call) Run(run func(ctx context.Context, path string)) *MockAddFileUsecase_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAddFileUsecase_ReadFile_Call) Return(_a0 []byte, _a1 error) *MockAddFileUsecase_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAddFileUsecase_ReadFile_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockAddFileUsecase_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockAddFileUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockAddFileUsecase creates a new instance of MockAddFileUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAddFileUsecase(t mockConstructorTestingTNewMockAddFileUsecase) *MockAddFileUsecase {
	mock := &MockAddFileUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
