// Code generated by mockery v2.26.1. DO NOT EDIT.

package command

import (
	context "context"

	models "github.com/Puena/password-keeper/client/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockEditCreditCardUsecase is an autogenerated mock type for the EditCreditCardUsecase type
type MockEditCreditCardUsecase struct {
	mock.Mock
}

type MockEditCreditCardUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEditCreditCardUsecase) EXPECT() *MockEditCreditCardUsecase_Expecter {
	return &MockEditCreditCardUsecase_Expecter{mock: &_m.Mock}
}

// EditCard provides a mock function with given fields: ctx, name, newName, newCard, lockPassword
func (_m *MockEditCreditCardUsecase) EditCard(ctx context.Context, name string, newName string, newCard *models.Card, lockPassword string) error {
	ret := _m.Called(ctx, name, newName, newCard, lockPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *models.Card, string) error); ok {
		r0 = rf(ctx, name, newName, newCard, lockPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEditCreditCardUsecase_EditCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditCard'
type MockEditCreditCardUsecase_EditCard_Call struct {
	*mock.Call
}

// EditCard is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - newName string
//   - newCard *models.Card
//   - lockPassword string
func (_e *MockEditCreditCardUsecase_Expecter) EditCard(ctx interface{}, name interface{}, newName interface{}, newCard interface{}, lockPassword interface{}) *MockEditCreditCardUsecase_EditCard_Call {
	return &MockEditCreditCardUsecase_EditCard_Call{Call: _e.mock.On("EditCard", ctx, name, newName, newCard, lockPassword)}
}

func (_c *MockEditCreditCardUsecase_EditCard_Call) Run(run func(ctx context.Context, name string, newName string, newCard *models.Card, lockPassword string)) *MockEditCreditCardUsecase_EditCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*models.Card), args[4].(string))
	})
	return _c
}

func (_c *MockEditCreditCardUsecase_EditCard_Call) Return(_a0 error) *MockEditCreditCardUsecase_EditCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditCreditCardUsecase_EditCard_Call) RunAndReturn(run func(context.Context, string, string, *models.Card, string) error) *MockEditCreditCardUsecase_EditCard_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractUserError provides a mock function with given fields: err
func (_m *MockEditCreditCardUsecase) ExtractUserError(err error) error {
	ret := _m.Called(err)

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEditCreditCardUsecase_ExtractUserError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractUserError'
type MockEditCreditCardUsecase_ExtractUserError_Call struct {
	*mock.Call
}

// ExtractUserError is a helper method to define mock.On call
//   - err error
func (_e *MockEditCreditCardUsecase_Expecter) ExtractUserError(err interface{}) *MockEditCreditCardUsecase_ExtractUserError_Call {
	return &MockEditCreditCardUsecase_ExtractUserError_Call{Call: _e.mock.On("ExtractUserError", err)}
}

func (_c *MockEditCreditCardUsecase_ExtractUserError_Call) Run(run func(err error)) *MockEditCreditCardUsecase_ExtractUserError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockEditCreditCardUsecase_ExtractUserError_Call) Return(_a0 error) *MockEditCreditCardUsecase_ExtractUserError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditCreditCardUsecase_ExtractUserError_Call) RunAndReturn(run func(error) error) *MockEditCreditCardUsecase_ExtractUserError_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockEditCreditCardUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEditCreditCardUsecase creates a new instance of MockEditCreditCardUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEditCreditCardUsecase(t mockConstructorTestingTNewMockEditCreditCardUsecase) *MockEditCreditCardUsecase {
	mock := &MockEditCreditCardUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
