// Code generated by mockery v2.26.1. DO NOT EDIT.

package command

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGetPasswordUsecase is an autogenerated mock type for the GetPasswordUsecase type
type MockGetPasswordUsecase struct {
	mock.Mock
}

type MockGetPasswordUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetPasswordUsecase) EXPECT() *MockGetPasswordUsecase_Expecter {
	return &MockGetPasswordUsecase_Expecter{mock: &_m.Mock}
}

// ExtractUserError provides a mock function with given fields: err
func (_m *MockGetPasswordUsecase) ExtractUserError(err error) error {
	ret := _m.Called(err)

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGetPasswordUsecase_ExtractUserError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractUserError'
type MockGetPasswordUsecase_ExtractUserError_Call struct {
	*mock.Call
}

// ExtractUserError is a helper method to define mock.On call
//   - err error
func (_e *MockGetPasswordUsecase_Expecter) ExtractUserError(err interface{}) *MockGetPasswordUsecase_ExtractUserError_Call {
	return &MockGetPasswordUsecase_ExtractUserError_Call{Call: _e.mock.On("ExtractUserError", err)}
}

func (_c *MockGetPasswordUsecase_ExtractUserError_Call) Run(run func(err error)) *MockGetPasswordUsecase_ExtractUserError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockGetPasswordUsecase_ExtractUserError_Call) Return(_a0 error) *MockGetPasswordUsecase_ExtractUserError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGetPasswordUsecase_ExtractUserError_Call) RunAndReturn(run func(error) error) *MockGetPasswordUsecase_ExtractUserError_Call {
	_c.Call.Return(run)
	return _c
}

// GetPasswordByName provides a mock function with given fields: ctx, name, lockPassword
func (_m *MockGetPasswordUsecase) GetPasswordByName(ctx context.Context, name string, lockPassword string) (string, error) {
	ret := _m.Called(ctx, name, lockPassword)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, name, lockPassword)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, name, lockPassword)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, lockPassword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetPasswordUsecase_GetPasswordByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPasswordByName'
type MockGetPasswordUsecase_GetPasswordByName_Call struct {
	*mock.Call
}

// GetPasswordByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - lockPassword string
func (_e *MockGetPasswordUsecase_Expecter) GetPasswordByName(ctx interface{}, name interface{}, lockPassword interface{}) *MockGetPasswordUsecase_GetPasswordByName_Call {
	return &MockGetPasswordUsecase_GetPasswordByName_Call{Call: _e.mock.On("GetPasswordByName", ctx, name, lockPassword)}
}

func (_c *MockGetPasswordUsecase_GetPasswordByName_Call) Run(run func(ctx context.Context, name string, lockPassword string)) *MockGetPasswordUsecase_GetPasswordByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGetPasswordUsecase_GetPasswordByName_Call) Return(_a0 string, _a1 error) *MockGetPasswordUsecase_GetPasswordByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetPasswordUsecase_GetPasswordByName_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockGetPasswordUsecase_GetPasswordByName_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockGetPasswordUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockGetPasswordUsecase creates a new instance of MockGetPasswordUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockGetPasswordUsecase(t mockConstructorTestingTNewMockGetPasswordUsecase) *MockGetPasswordUsecase {
	mock := &MockGetPasswordUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
