// Code generated by mockery v2.26.1. DO NOT EDIT.

package command

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRegisterUsecase is an autogenerated mock type for the RegisterUsecase type
type MockRegisterUsecase struct {
	mock.Mock
}

type MockRegisterUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegisterUsecase) EXPECT() *MockRegisterUsecase_Expecter {
	return &MockRegisterUsecase_Expecter{mock: &_m.Mock}
}

// ExtractUserError provides a mock function with given fields: err
func (_m *MockRegisterUsecase) ExtractUserError(err error) error {
	ret := _m.Called(err)

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegisterUsecase_ExtractUserError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractUserError'
type MockRegisterUsecase_ExtractUserError_Call struct {
	*mock.Call
}

// ExtractUserError is a helper method to define mock.On call
//   - err error
func (_e *MockRegisterUsecase_Expecter) ExtractUserError(err interface{}) *MockRegisterUsecase_ExtractUserError_Call {
	return &MockRegisterUsecase_ExtractUserError_Call{Call: _e.mock.On("ExtractUserError", err)}
}

func (_c *MockRegisterUsecase_ExtractUserError_Call) Run(run func(err error)) *MockRegisterUsecase_ExtractUserError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockRegisterUsecase_ExtractUserError_Call) Return(_a0 error) *MockRegisterUsecase_ExtractUserError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegisterUsecase_ExtractUserError_Call) RunAndReturn(run func(error) error) *MockRegisterUsecase_ExtractUserError_Call {
	_c.Call.Return(run)
	return _c
}

// Registration provides a mock function with given fields: ctx, login, password
func (_m *MockRegisterUsecase) Registration(ctx context.Context, login string, password string) error {
	ret := _m.Called(ctx, login, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, login, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegisterUsecase_Registration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Registration'
type MockRegisterUsecase_Registration_Call struct {
	*mock.Call
}

// Registration is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *MockRegisterUsecase_Expecter) Registration(ctx interface{}, login interface{}, password interface{}) *MockRegisterUsecase_Registration_Call {
	return &MockRegisterUsecase_Registration_Call{Call: _e.mock.On("Registration", ctx, login, password)}
}

func (_c *MockRegisterUsecase_Registration_Call) Run(run func(ctx context.Context, login string, password string)) *MockRegisterUsecase_Registration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRegisterUsecase_Registration_Call) Return(_a0 error) *MockRegisterUsecase_Registration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegisterUsecase_Registration_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRegisterUsecase_Registration_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockRegisterUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRegisterUsecase creates a new instance of MockRegisterUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRegisterUsecase(t mockConstructorTestingTNewMockRegisterUsecase) *MockRegisterUsecase {
	mock := &MockRegisterUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
