// Code generated by mockery v2.26.1. DO NOT EDIT.

package command

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEditFileUsecase is an autogenerated mock type for the EditFileUsecase type
type MockEditFileUsecase struct {
	mock.Mock
}

type MockEditFileUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEditFileUsecase) EXPECT() *MockEditFileUsecase_Expecter {
	return &MockEditFileUsecase_Expecter{mock: &_m.Mock}
}

// EditFile provides a mock function with given fields: ctx, name, newName, newData, lockPassword
func (_m *MockEditFileUsecase) EditFile(ctx context.Context, name string, newName string, newData []byte, lockPassword string) error {
	ret := _m.Called(ctx, name, newName, newData, lockPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte, string) error); ok {
		r0 = rf(ctx, name, newName, newData, lockPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEditFileUsecase_EditFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditFile'
type MockEditFileUsecase_EditFile_Call struct {
	*mock.Call
}

// EditFile is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - newName string
//   - newData []byte
//   - lockPassword string
func (_e *MockEditFileUsecase_Expecter) EditFile(ctx interface{}, name interface{}, newName interface{}, newData interface{}, lockPassword interface{}) *MockEditFileUsecase_EditFile_Call {
	return &MockEditFileUsecase_EditFile_Call{Call: _e.mock.On("EditFile", ctx, name, newName, newData, lockPassword)}
}

func (_c *MockEditFileUsecase_EditFile_Call) Run(run func(ctx context.Context, name string, newName string, newData []byte, lockPassword string)) *MockEditFileUsecase_EditFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte), args[4].(string))
	})
	return _c
}

func (_c *MockEditFileUsecase_EditFile_Call) Return(_a0 error) *MockEditFileUsecase_EditFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditFileUsecase_EditFile_Call) RunAndReturn(run func(context.Context, string, string, []byte, string) error) *MockEditFileUsecase_EditFile_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractUserError provides a mock function with given fields: err
func (_m *MockEditFileUsecase) ExtractUserError(err error) error {
	ret := _m.Called(err)

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEditFileUsecase_ExtractUserError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractUserError'
type MockEditFileUsecase_ExtractUserError_Call struct {
	*mock.Call
}

// ExtractUserError is a helper method to define mock.On call
//   - err error
func (_e *MockEditFileUsecase_Expecter) ExtractUserError(err interface{}) *MockEditFileUsecase_ExtractUserError_Call {
	return &MockEditFileUsecase_ExtractUserError_Call{Call: _e.mock.On("ExtractUserError", err)}
}

func (_c *MockEditFileUsecase_ExtractUserError_Call) Run(run func(err error)) *MockEditFileUsecase_ExtractUserError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockEditFileUsecase_ExtractUserError_Call) Return(_a0 error) *MockEditFileUsecase_ExtractUserError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditFileUsecase_ExtractUserError_Call) RunAndReturn(run func(error) error) *MockEditFileUsecase_ExtractUserError_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function with given fields: ctx, path
func (_m *MockEditFileUsecase) ReadFile(ctx context.Context, path string) ([]byte, error) {
	ret := _m.Called(ctx, path)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEditFileUsecase_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockEditFileUsecase_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockEditFileUsecase_Expecter) ReadFile(ctx interface{}, path interface{}) *MockEditFileUsecase_ReadFile_Call {
	return &MockEditFileUsecase_ReadFile_Call{Call: _e.mock.On("ReadFile", ctx, path)}
}

func (_c *MockEditFileUsecase_ReadFile_Call) Run(run func(ctx context.Context, path string)) *MockEditFileUsecase_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockEditFileUsecase_ReadFile_Call) Return(_a0 []byte, _a1 error) *MockEditFileUsecase_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEditFileUsecase_ReadFile_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockEditFileUsecase_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockEditFileUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEditFileUsecase creates a new instance of MockEditFileUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEditFileUsecase(t mockConstructorTestingTNewMockEditFileUsecase) *MockEditFileUsecase {
	mock := &MockEditFileUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
