// Code generated by mockery v2.26.1. DO NOT EDIT.

package command

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGetFileUsecase is an autogenerated mock type for the GetFileUsecase type
type MockGetFileUsecase struct {
	mock.Mock
}

type MockGetFileUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetFileUsecase) EXPECT() *MockGetFileUsecase_Expecter {
	return &MockGetFileUsecase_Expecter{mock: &_m.Mock}
}

// ExtractUserError provides a mock function with given fields: err
func (_m *MockGetFileUsecase) ExtractUserError(err error) error {
	ret := _m.Called(err)

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGetFileUsecase_ExtractUserError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractUserError'
type MockGetFileUsecase_ExtractUserError_Call struct {
	*mock.Call
}

// ExtractUserError is a helper method to define mock.On call
//   - err error
func (_e *MockGetFileUsecase_Expecter) ExtractUserError(err interface{}) *MockGetFileUsecase_ExtractUserError_Call {
	return &MockGetFileUsecase_ExtractUserError_Call{Call: _e.mock.On("ExtractUserError", err)}
}

func (_c *MockGetFileUsecase_ExtractUserError_Call) Run(run func(err error)) *MockGetFileUsecase_ExtractUserError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockGetFileUsecase_ExtractUserError_Call) Return(_a0 error) *MockGetFileUsecase_ExtractUserError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGetFileUsecase_ExtractUserError_Call) RunAndReturn(run func(error) error) *MockGetFileUsecase_ExtractUserError_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByName provides a mock function with given fields: ctx, name, lockPassword
func (_m *MockGetFileUsecase) GetFileByName(ctx context.Context, name string, lockPassword string) ([]byte, error) {
	ret := _m.Called(ctx, name, lockPassword)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, error)); ok {
		return rf(ctx, name, lockPassword)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = rf(ctx, name, lockPassword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, lockPassword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetFileUsecase_GetFileByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByName'
type MockGetFileUsecase_GetFileByName_Call struct {
	*mock.Call
}

// GetFileByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - lockPassword string
func (_e *MockGetFileUsecase_Expecter) GetFileByName(ctx interface{}, name interface{}, lockPassword interface{}) *MockGetFileUsecase_GetFileByName_Call {
	return &MockGetFileUsecase_GetFileByName_Call{Call: _e.mock.On("GetFileByName", ctx, name, lockPassword)}
}

func (_c *MockGetFileUsecase_GetFileByName_Call) Run(run func(ctx context.Context, name string, lockPassword string)) *MockGetFileUsecase_GetFileByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGetFileUsecase_GetFileByName_Call) Return(_a0 []byte, _a1 error) *MockGetFileUsecase_GetFileByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetFileUsecase_GetFileByName_Call) RunAndReturn(run func(context.Context, string, string) ([]byte, error)) *MockGetFileUsecase_GetFileByName_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function with given fields: ctx, path, data
func (_m *MockGetFileUsecase) WriteFile(ctx context.Context, path string, data []byte) error {
	ret := _m.Called(ctx, path, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, path, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGetFileUsecase_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockGetFileUsecase_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - data []byte
func (_e *MockGetFileUsecase_Expecter) WriteFile(ctx interface{}, path interface{}, data interface{}) *MockGetFileUsecase_WriteFile_Call {
	return &MockGetFileUsecase_WriteFile_Call{Call: _e.mock.On("WriteFile", ctx, path, data)}
}

func (_c *MockGetFileUsecase_WriteFile_Call) Run(run func(ctx context.Context, path string, data []byte)) *MockGetFileUsecase_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockGetFileUsecase_WriteFile_Call) Return(_a0 error) *MockGetFileUsecase_WriteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGetFileUsecase_WriteFile_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockGetFileUsecase_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockGetFileUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockGetFileUsecase creates a new instance of MockGetFileUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockGetFileUsecase(t mockConstructorTestingTNewMockGetFileUsecase) *MockGetFileUsecase {
	mock := &MockGetFileUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
